---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.8.8' }]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-17-10-x64
    driver: digitalocean
    driver_config:
      region: nyc1
      size: 1gb

suites:
  - name: default
    data_bags_path: test/fixtures/default/data_bags
    run_list:
      - recipe[transit.tips::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
